---

- name: Gather Facts
  setup:
  tags:
    - always

- include: ubuntu.yml
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  
- include: freebsd.yml
  when: ansible_distribution == 'FreeBSD'

- name: Install tools
  package: name="{{ item }}" state=present
  with_items:
    - "{{ tools }}"
  tags:
    - always

- name: Enable packet forwarding for IPv4
  sysctl: name="{{ item }}" value=1
  with_items:
    - "{{ sysctl.forwarding }}"
  tags:
    - always
